# Generated by Django 3.1.7 on 2021-08-01 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('start_timestamp', models.DateTimeField(blank=True, null=True)),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('sent', 'sent'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('completed', 'completed'), ('paid', 'paid')], max_length=50, null=True)),
                ('requested_services', models.JSONField(blank=True, default=list, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_by', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
