# Generated by Django 3.1.7 on 2021-09-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_requests', '0002_auto_20210801_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsession',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
