# Generated by Django 3.1.7 on 2021-07-19 12:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Expertise Name(s)',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
        migrations.AddField(
            model_name='user',
            name='location_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
