# Generated by Django 3.1.7 on 2021-07-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210719_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_complete',
            field=models.BooleanField(default=False),
        ),
    ]
