# Generated by Django 3.1.7 on 2021-07-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userexpertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexpertise',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userexpertise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
