# Generated by Django 3.1.7 on 2021-07-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210723_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpertise',
            name='experience_in_years',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
