# Generated by Django 3.1.7 on 2021-07-25 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210723_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStripeVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_front_picture', models.FileField(blank=True, null=True, upload_to='stripe_docs/', validators=[helpers.validators.validate_file])),
                ('document_back_picture', models.FileField(blank=True, null=True, upload_to='stripe_docs/', validators=[helpers.validators.validate_file])),
                ('certificate', models.FileField(blank=True, null=True, upload_to='stripe_docs/', validators=[helpers.validators.validate_file])),
                ('bank_account_number', models.CharField(blank=True, max_length=60, null=True)),
                ('bank_sort_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('errors', models.JSONField(blank=True, default=list, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User(s) Address Proof and Certificates',
            },
        ),
    ]
