# Generated by Django 3.1.7 on 2021-07-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userstripeverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
