# Generated by Django 3.1.7 on 2021-08-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210801_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_info_added',
            field=models.BooleanField(default=False),
        ),
    ]
