# Generated by Django 3.1.7 on 2021-08-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210804_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexpertise',
            name='user_defined_expertise',
            field=models.CharField(blank=True, help_text='Expertise defined by User', max_length=256, null=True),
        ),
    ]
