# Generated by Django 3.1.7 on 2021-09-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('professional', 'professional'), ('customer', 'customer')], max_length=30, null=True),
        ),
    ]
