# Generated by Django 3.1.7 on 2021-08-31 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_requests', '0002_auto_20210801_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_id', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_requests.bookingsession')),
            ],
        ),
    ]
