# Generated by Django 3.1.7 on 2021-08-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikesAndComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('likes_extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('comments_extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('photo_liked', models.BooleanField(default=False)),
                ('image_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to='user_feed.userimage')),
            ],
        ),
    ]
