# Generated by Django 3.1.7 on 2021-08-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_feed', '0004_userimage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='type_of_action',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('comment', 'comment')], max_length=20, null=True),
        ),
    ]
