# Generated by Django 3.1.7 on 2021-08-15 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_feed', '0006_auto_20210815_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikesandcomment',
            name='comments_extra_data',
        ),
        migrations.AddField(
            model_name='userlikesandcomment',
            name='commented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
