# Generated by Django 3.1.7 on 2021-09-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_inappnotification_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='review_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
